-- Conquest of Azeroth: map sizes for the client's custom maps that Questie-X and this plugin don't know,
-- generated by tools\questie-x\gen_coa_maps.py from the client's WorldMapArea.dbc. Map ids are the
-- client's GetCurrentMapAreaID() (WorldMapArea.ID + 1). Only sizes, no sub-zone folding: Questie's
-- InjectZoneTables would also point the parent zone at the sub-map and move the zone's pins onto it.
-- Merged with the plugin's own map data, which AscensionLoader then injects (fill-gaps only).
local _, addonTable = ...
if not addonTable then return end

local coaMaps = {
	[1201] = { [1] = 570.000, [2] = 380.000, [3] = -1902.500, [4] = -490.000, instance = 1, mapID = 1201, name = "Wailing Caverns", mapType = 3, parentMapID = 718 }, -- wailingcavernsbarrens
	[1203] = { [1] = 1306.000, [2] = 870.670, [3] = -3707.500, [4] = -8036.660, instance = 1, mapID = 1203, name = "Caverns of Time", mapType = 3, parentMapID = 10145 }, -- cavernsoftimein
	[1204] = { [1] = 1107.510, [2] = 738.330, [3] = -4163.740, [4] = -7955.830, instance = 1, mapID = 1204, name = "Caverns of Time", mapType = 3, parentMapID = 10113 }, -- cavernsoftime
	[1205] = { [1] = 712.500, [2] = 475.000, [3] = -761.250, [4] = -7325.000, instance = 0, mapID = 1205, name = "Blackrock Mountain", mapType = 3, parentMapID = 25 }, -- blackrockmountain
	[1206] = { [1] = 255.000, [2] = 170.000, [3] = -1145.000, [4] = -7480.000, instance = 0, mapID = 1206, name = "Blackrock Mountain", mapType = 3, parentMapID = 10114 }, -- upperblackrockmountain
	[1207] = { [1] = 760.030, [2] = 506.690, [3] = -627.480, [4] = -7086.650, instance = 0, mapID = 1207, name = "Blackrock Mountain", mapType = 3, parentMapID = 10115 }, -- lowerblackrockmountain
	[1208] = { [1] = 600.000, [2] = 400.000, [3] = 3085.500, [4] = -1250.000, instance = 1, mapID = 1208, name = "Maraudon", mapType = 3, parentMapID = 2100 }, -- maraudonorange
	[1209] = { [1] = 560.030, [2] = 373.350, [3] = 3165.010, [4] = -1092.320, instance = 1, mapID = 1209, name = "Maraudon", mapType = 3, parentMapID = 10116 }, -- maraudonpurple
	[1210] = { [1] = 562.500, [2] = 375.000, [3] = -2748.750, [4] = -5955.000, instance = 0, mapID = 1210, name = "Uldaman", mapType = 3, parentMapID = 1337 }, -- Uldamanin
	[1211] = { [1] = 475.000, [2] = 316.670, [3] = -12247.500, [4] = -3009.160, instance = 1, mapID = 1211, name = "Stillpine Hold", mapType = 3, parentMapID = 10117 }, -- stillpinehold
	[1212] = { [1] = 375.000, [2] = 250.000, [3] = -11369.000, [4] = -4640.000, instance = 1, mapID = 1212, name = "Tides' Hollow", mapType = 3, parentMapID = 3569 }, -- tideshollow
	[1218] = { [1] = 258.000, [2] = 172.000, [3] = -4622.500, [4] = 971.250, instance = 1, mapID = 1218, name = "Dustwind Cave", mapType = 3, parentMapID = 371 }, -- dustwindcave
	[1223] = { [1] = 300.000, [2] = 200.000, [3] = -7180.000, [4] = 7710.000, instance = 0, mapID = 1223, name = "Amani Catacombs", mapType = 3, parentMapID = 10127 }, -- amanicatacombs
	[1227] = { [1] = 252.510, [2] = 168.340, [3] = 161.255, [4] = -6183.330, instance = 1, mapID = 1227, name = "Twilight's Run", mapType = 3, parentMapID = 3446 }, -- twilightsrun
	[1228] = { [1] = 750.000, [2] = 500.000, [3] = -2190.000, [4] = -7640.000, instance = 1, mapID = 1228, name = "The Noxious Lair", mapType = 3, parentMapID = 10131 }, -- thenoxiouslair
	[1229] = { [1] = 885.000, [2] = 590.000, [3] = -3612.500, [4] = -8900.000, instance = 1, mapID = 1229, name = "The Gaping Chasm", mapType = 3, parentMapID = 10132 }, -- thegapingchasm
	[1234] = { [1] = 382.500, [2] = 255.000, [3] = -983.750, [4] = -7930.000, instance = 1, mapID = 1234, name = "The Slithering Scar", mapType = 3, parentMapID = 10134 }, -- theslitheringscar
	[1235] = { [1] = 450.000, [2] = 300.000, [3] = 1792.500, [4] = -11055.000, instance = 0, mapID = 1235, name = "The Deadmines", mapType = 3, parentMapID = 10135 }, -- deadmineswestfall
	[1236] = { [1] = 262.500, [2] = 175.000, [3] = 2096.250, [4] = -10430.000, instance = 0, mapID = 1236, name = "Gold Coast Quarry", mapType = 3, parentMapID = 10136 }, -- goldcoastquarry
	[1237] = { [1] = 277.000, [2] = 184.660, [3] = 1570.500, [4] = -9798.670, instance = 0, mapID = 1237, name = "Jangolode Mine", mapType = 3, parentMapID = 10137 }, -- jangolodemine
	[1242] = { [1] = 1818.700, [2] = 1212.500, [3] = -12814.600, [4] = -3604.170, instance = 530, mapID = 1242, name = "Ammen Vale", mapType = 3, parentMapID = 10142 }, -- ammenvalestart
	[2032] = { [1] = -123.000, [2] = 195.000, [3] = 4890.000, [4] = -6813.000, instance = 1, mapID = 2032, name = "Xorthal's Lair", mapType = 3, parentMapID = 5366 }, -- Xorthal's Lair
	[2040] = { [1] = 743.290, [2] = 495.530, [3] = 2795.240, [4] = -4408.890, instance = 1, mapID = 2040, name = "Depthbreaker's Hollow", mapType = 3, parentMapID = 10239 }, -- DepthbreakerHollow
	[2063] = { [1] = 3631.870, [2] = 2421.250, [3] = 2214.230, [4] = -6003.880, instance = 0, mapID = 2063, name = "Pale Reach", mapType = 3, parentMapID = 10302 }, -- Scadeald
	[2064] = { [1] = 5097.130, [2] = 3398.080, [3] = 4010.910, [4] = -3244.710, instance = 0, mapID = 2064, name = "Druk'Thar", mapType = 3, parentMapID = 10292 }, -- Palehorn
	[2067] = { [1] = 801.972, [2] = 534.640, [3] = 154.441, [4] = -6307.520, instance = 0, mapID = 2067, name = "Dun Kazad", mapType = 3, parentMapID = 10306 }, -- DunKazad
}

local merged = {}
local base = AscensionUiMapData and AscensionUiMapData.uiMapData
if base then for id, data in pairs(base) do merged[id] = data end end
for id, data in pairs(coaMaps) do if merged[id] == nil then merged[id] = data end end
addonTable.uiMapData = merged
