"""Generates Questie-X-AscensionDB/Zones/CoAExtraZones.lua: map sizes for the Conquest of Azeroth client's
custom maps (sub-zones, caves, CoA zones) that neither Questie-X nor its Ascension plugin know.

Source: the client's own DBFilesClient\\WorldMapArea.dbc (and AreaTable.dbc for names), read from its MPQs.
The client's GetCurrentMapAreaID() is WorldMapArea.ID + 1, the numbering Questie and the plugin use.

Only map sizes are added, never the plugin's sub-zone -> parent-zone folding: Questie's InjectZoneTables
also points the parent area at the sub-map (areaIdToUiMapId[12] = <a mine>), which would move a whole
zone's pins onto a small map.

    python gen_coa_maps.py            write the Lua file next to this script (review it, then install)
"""
import glob, os, re, struct, sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mpq import MPQ

CLIENT = os.environ.get("COA_CLIENT", r"D:\COA Client")  # set COA_CLIENT to your client folder
DATA = os.path.join(CLIENT, "Data")
ADDONS = os.path.join(CLIENT, "Interface", "AddOns")
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "CoAExtraZones.lua")


def read_dbc(name):
    found = None
    for p in sorted(glob.glob(os.path.join(DATA, "*.MPQ")) + glob.glob(os.path.join(DATA, "*.mpq")), key=str.lower):
        try:
            d = MPQ(p).read("DBFilesClient\\" + name)
        except Exception:
            d = None
        if d:
            found = d  # the last archive in load order wins
    magic, n, nf, rs, ss = struct.unpack_from("<4s4I", found, 0)
    strings = found[20 + n * rs:]

    def text(off):
        return strings[off:strings.find(b"\0", off)].decode("utf-8", "replace")
    rows = []
    for i in range(n):
        raw = found[20 + i * rs:20 + (i + 1) * rs]
        rows.append((struct.unpack_from("<%di" % nf, raw), struct.unpack_from("<%df" % nf, raw), text))
    return rows


def lua_keys(path, pattern):
    with open(path, encoding="latin-1") as f:
        return {int(k) for k in re.findall(pattern, f.read(), re.M)}


area_names = {ints[0]: text(ints[11]) for ints, _, text in read_dbc("AreaTable.dbc")}

core_map = os.path.join(ADDONS, "Questie-X", "Compat", "UiMapData.lua")
plugin_map = os.path.join(ADDONS, "Questie-X-AscensionDB", "Zones", "AscensionUiMapData.lua")
known = (lua_keys(core_map, r"^\s*\[(\d+)\]\s*=\s*\{")            # Questie's uiMapIds
         | lua_keys(core_map, r"\[?\"?mapID\"?\]?\s*=\s*(\d+)")     # client map ids Questie already maps
         | lua_keys(plugin_map, r"^\s*\[(\d+)\]\s*=\s*\{"))        # the plugin's maps

entries = []
for ints, floats, text in read_dbc("WorldMapArea.dbc"):
    wma_id, map_id, area_id = ints[0], ints[1], ints[2]
    left, right, top, bottom = floats[4:8]
    ui = wma_id + 1
    if area_id == 0 or ui in known or left == right or top == bottom:
        continue  # continents/world, maps Questie already has, and maps without bounds
    if map_id not in (0, 1, 530, 571):
        continue  # open world only: dungeons/raids/battlegrounds/dev maps use Questie's own floor handling
    name = area_names.get(area_id) or text(ints[3])
    entries.append((ui, map_id, area_id, name, text(ints[3]), left - right, top - bottom, left, top))

entries.sort()
with open(OUT, "w", encoding="utf-8", newline="\r\n") as f:
    f.write("-- Conquest of Azeroth: map sizes for the client's custom maps that Questie-X and this plugin don't know,\n"
            "-- generated by tools\\questie-x\\gen_coa_maps.py from the client's WorldMapArea.dbc. Map ids are the\n"
            "-- client's GetCurrentMapAreaID() (WorldMapArea.ID + 1). Only sizes, no sub-zone folding: Questie's\n"
            "-- InjectZoneTables would also point the parent zone at the sub-map and move the zone's pins onto it.\n"
            "-- Merged with the plugin's own map data, which AscensionLoader then injects (fill-gaps only).\n"
            "local _, addonTable = ...\n"
            "if not addonTable then return end\n\n"
            "local coaMaps = {\n")
    for ui, map_id, area_id, name, mapfile, width, height, left, top in entries:
        f.write('\t[%d] = { [1] = %.3f, [2] = %.3f, [3] = %.3f, [4] = %.3f, instance = %d, mapID = %d, '
                'name = "%s", mapType = 3, parentMapID = %d }, -- %s\n'
                % (ui, width, height, left, top, map_id, ui, name.replace('"', '\\"'), area_id, mapfile))
    f.write("}\n\n"
            "local merged = {}\n"
            "local base = AscensionUiMapData and AscensionUiMapData.uiMapData\n"
            "if base then for id, data in pairs(base) do merged[id] = data end end\n"
            "for id, data in pairs(coaMaps) do if merged[id] == nil then merged[id] = data end end\n"
            "addonTable.uiMapData = merged\n")
print("%d custom maps written to %s" % (len(entries), OUT))
for e in entries:
    print("  %5d  map %-3d  %-32s %s" % (e[0], e[1], e[3], e[4]))
